version: "3.8"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command:
      [
        "./wait-for-es.sh",
        "http://elasticsearch:9200",
        "poetry",
        "run",
        "python",
        "main.py",
      ]
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - elasticnet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    healthcheck:
      test:
        ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.license.self_generated.type=basic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elasticnet

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elasticnet

  redis_quote:
    container_name: redis_quote
    image: redis:7-alpine
    networks:
      - elasticnet

  celery_worker_quote:
    container_name: celery_worker_quote
    build: .
    command:
      [
        "poetry",
        "run",
        "celery",
        "-A",
        "app.core.workers.celery_worker.celery_app",
        "worker",
      ]
    environment:
      - CELERY_BROKER_URL=redis://redis_quote:6379/0
      - CELERY_RESULT_BACKEND=redis://redis_quote:6379/0
    depends_on:
      - api
      - redis_quote
    networks:
      - elasticnet


  flower_quote:
    container_name: flower_quote
    build: .
    command:
      [
        "poetry",
        "run",
        "celery",
        "-A",
        "app.core.workers.celery_worker.celery_app",
        "flower",
        "--port=5555",
      ]
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
    depends_on:
      - api
      - redis_quote
      - celery_worker_quote
    networks:
      - elasticnet

networks:
  elasticnet:

volumes:
  esdata1:
